trigger:
- development

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  BuildSource: 'src'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
- job: CI
  timeoutInMinutes: 120

  strategy:
    matrix:
      Linux_Build_and_Test:
        imageName: 'ubuntu-20.04'
      Windows_Build_and_Test:
        imageName: 'windows-2019'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK 2.2.207 (SonarCloud)'
    inputs:
      version: 2.2.207

  - task: UseDotNet@2
    displayName: 'Use .Net Core 3.1.401'
    inputs:
      version: 3.1.401

  - task: DotNetCoreCLI@2
    displayName: 'Install NBGV tool'
    inputs:
      command: custom
      custom: tool
      arguments: 'install --global nbgv'

  - task: DotNetCoreCLI@2
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Install ReportGenerator tool'
    inputs:
      command: custom
      custom: tool
      arguments: install --global dotnet-reportgenerator-globaltool

  - script: 'nbgv cloud'
    displayName: 'Set Version using NBGV'

  - task: DownloadSecureFile@1
    displayName: 'Download cuemon.snk'
    inputs:
      secureFile: 'cuemon.snk'

  - task: CopyFiles@2
    displayName: 'Copy cuemon.snk to $(System.DefaultWorkingDirectory)'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: cuemon.snk
      TargetFolder: '$(System.DefaultWorkingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: **/*.csproj

  - task: SonarCloudPrepare@1
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Prepare Analysis on SonarCloud'
    inputs:
      SonarCloud: 'Cuemon-SonarCloud'
      organization: 'geekle'
      scannerMode: 'MSBuild'
      projectKey: 'Cuemon'
      projectName: 'Cuemon'
      projectVersion: '$(GitAssemblyInformationalVersion)'
      extraProperties: |
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/*opencover.xml
        sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

  - task: DotNetCoreCLI@2
    displayName: 'Build netcoreapp3.0 compatible Assemblies'
    inputs:
      command: 'build'
      projects: |
        src/**/Cuemon.AspNetCore*.csproj
        src/**/Cuemon.Extensions.AspNetCore*.csproj
        src/**/Cuemon.Extensions.Xunit.csproj
      arguments: '--configuration $(BuildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/netcoreapp3.0 --framework netcoreapp3.0'
      workingDirectory: '$(BuildSource)'

  - task: DotNetCoreCLI@2
    displayName: 'Build netstandard2.1 compatible Assemblies'
    inputs:
      command: 'build'
      projects: |
        src/**/Cuemon.Extensions.IO.csproj
        src/**/Cuemon.IO.csproj
      arguments: '--configuration $(BuildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/netstandard2.1 --framework netstandard2.1'
      workingDirectory: '$(BuildSource)'

  - task: DotNetCoreCLI@2
    displayName: 'Build netstandard2.0 compatible Assemblies'
    inputs:
      command: 'build'
      projects: src/**/*.csproj
      arguments: '--configuration $(BuildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/netstandard2.0 --framework netstandard2.0'
      workingDirectory: '$(BuildSource)'

  - task: DotNetCoreCLI@2
    displayName: 'Test Solution'
    inputs:
      command: 'test'
      projects: test/**/*.csproj
      arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      publishTestResults: true

  - script: reportgenerator "-reports:**/*.opencover.xml" "-targetdir:$(Build.SourcesDirectory)/Coverage" "-reporttypes:Cobertura;HTMLInline;HTMLChart"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Create Code Coverage Reports'

  - task: PublishCodeCoverageResults@1
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/Coverage/Cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/Coverage'

  - task: SonarCloudAnalyze@1
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Run Sonar Cloud Code Analysis'

  - task: SonarCloudPublish@1
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Publish Quality Gate Result to Sonar Cloud'
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish compiled DLLs'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: Packages
      publishLocation: Container