name: $(DayOfYear)$(Rev:rr)
trigger:
  branches:
    include:
    - development
  paths:
    exclude:
    - .github/
    - .nuget/
    - .pipelines/
    - docfx/
    - azure-pipelines.yml
    - BuildDocfxImage.ps1
    - docker-compose.yml
    - Dockerfile.docfx
    - LICENSE.md
    - README.md
    - version.json

pr: none

variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

stages:
  - ${{ if endsWith(variables['build.sourceBranch'], 'development') }}:
    - template: .pipelines/azure-pipelines-stages.development.yml
  - ${{ if endsWith(variables['build.sourceBranch'], 'release') }}:
    - template: .pipelines/azure-pipelines-stages.staging.yml
  - ${{ if endsWith(variables['build.sourceBranch'], 'master') }}:
    - template: .pipelines/azure-pipelines-stages.production.yml
