trigger:
  branches:
    include:
    - development
    - release
    - master

  paths:
    exclude:
    - .github/
    - .pipelines/
    - docfx/
    - azure-pipelines.yml
    - BuildDocfxImage.ps1
    - docker-compose.yml
    - Dockerfile.docfx
    - LICENSE.md
    - README.md

variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

stages:
  - stage: BuildDevelopment
    displayName: 'Build for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Debug'
    jobs:
    - template: .pipelines/azure-pipelines-build.development.yml

  - stage: BuildRelease
    displayName: 'Build for release branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'release'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: .pipelines/azure-pipelines-build.staging.yml

  - stage: BuildMaster
    displayName: 'Build for master branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'master'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: .pipelines/azure-pipelines-build.production.yml

  - stage: DeployDevelopment
    displayName: 'Deployment for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    dependsOn: BuildDevelopment
    variables:
    - group: BuildSecrets
    jobs:
    - template: .pipelines/azure-pipelines-release.development.yml

  - stage: DeployRelease
    displayName: 'Deployment for release branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'release'))
    dependsOn: BuildRelease
    variables:
    - group: BuildSecrets
    jobs:
    - template: .pipelines/azure-pipelines-release.staging.yml

  - stage: DeployMaster
    displayName: 'Deployment for master branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'master'))
    dependsOn: BuildMaster
    variables:
    - group: BuildSecrets
    jobs:
    - template: .pipelines/azure-pipelines-release.production.yml