trigger:
- development

variables:
  BuildSource: 'src'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

jobs:
- job: CI
  timeoutInMinutes: 360

  pool:
    vmImage: 'windows-2019'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK 2.2.207 (SonarCloud)'
    inputs:
      version: 2.2.207

  - task: UseDotNet@2
    displayName: 'Use .Net Core 3.1.401'
    inputs:
      version: 3.1.401

  - task: DotNetCoreCLI@2
    displayName: 'Install NBGV tool'
    inputs:
      command: custom
      custom: tool
      arguments: 'install --global nbgv'

  - script: 'nbgv cloud'
    displayName: 'Set Version using NBGV'

  - task: DownloadSecureFile@1
    displayName: 'Download cuemon.snk'
    inputs:
      secureFile: 'cuemon.snk'

  - task: CopyFiles@2
    displayName: 'Copy cuemon.snk to $(System.DefaultWorkingDirectory)'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: cuemon.snk
      TargetFolder: '$(System.DefaultWorkingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/Cuemon.Core.csproj'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Cuemon-SonarCloud'
      organization: 'geekle'
      scannerMode: 'MSBuild'
      projectKey: 'Cuemon'
      projectName: 'Cuemon'
      projectVersion: '$(GitVersion.NuGetVersion)'

  - task: DotNetCoreCLI@2
    displayName: 'Build and Pack Assemblies'
    inputs:
      command: pack
      packagesToPack: 'src/**/Cuemon.Core.csproj'
      configuration: '$(BuildConfiguration)'
      packDirectory: '$(Build.ArtifactStagingDirectory)\artifacts'
      verbosityPack: Minimal

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: 'test/**/Cuemon.Core.Tests.csproj'
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - publish: $(Build.ArtifactStagingDirectory)\artifacts
    displayName: Publish Artifacts (Nuget)
    artifact: BuildPackages