// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``4(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.Caching.CacheInvalidation,System.Func{``1,``2,``3})~System.Func{``1,``2,``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``4(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.IDependency,System.Func{``1,``2,``3})~System.Func{``1,``2,``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``4(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.Collections.Generic.IEnumerable{Cuemon.Runtime.IDependency},System.Func{``1,``2,``3})~System.Func{``1,``2,``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``4(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.DateTime,System.Func{``1,``2,``3})~System.Func{``1,``2,``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``4(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.TimeSpan,System.Func{``1,``2,``3})~System.Func{``1,``2,``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``5(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.Caching.CacheInvalidation,System.Func{``1,``2,``3,``4})~System.Func{``1,``2,``3,``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``5(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.IDependency,System.Func{``1,``2,``3,``4})~System.Func{``1,``2,``3,``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``5(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.Collections.Generic.IEnumerable{Cuemon.Runtime.IDependency},System.Func{``1,``2,``3,``4})~System.Func{``1,``2,``3,``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``5(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.DateTime,System.Func{``1,``2,``3,``4})~System.Func{``1,``2,``3,``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``5(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.TimeSpan,System.Func{``1,``2,``3,``4})~System.Func{``1,``2,``3,``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``6(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.Caching.CacheInvalidation,System.Func{``1,``2,``3,``4,``5})~System.Func{``1,``2,``3,``4,``5}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``6(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.IDependency,System.Func{``1,``2,``3,``4,``5})~System.Func{``1,``2,``3,``4,``5}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``6(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.Collections.Generic.IEnumerable{Cuemon.Runtime.IDependency},System.Func{``1,``2,``3,``4,``5})~System.Func{``1,``2,``3,``4,``5}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``6(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.DateTime,System.Func{``1,``2,``3,``4,``5})~System.Func{``1,``2,``3,``4,``5}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``6(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.TimeSpan,System.Func{``1,``2,``3,``4,``5})~System.Func{``1,``2,``3,``4,``5}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``7(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.Caching.CacheInvalidation,System.Func{``1,``2,``3,``4,``5,``6})~System.Func{``1,``2,``3,``4,``5,``6}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``7(Cuemon.Runtime.Caching.ICacheEnumerable{``0},Cuemon.Runtime.IDependency,System.Func{``1,``2,``3,``4,``5,``6})~System.Func{``1,``2,``3,``4,``5,``6}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``7(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.Collections.Generic.IEnumerable{Cuemon.Runtime.IDependency},System.Func{``1,``2,``3,``4,``5,``6})~System.Func{``1,``2,``3,``4,``5,``6}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``7(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.DateTime,System.Func{``1,``2,``3,``4,``5,``6})~System.Func{``1,``2,``3,``4,``5,``6}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments (more under certain conditions).", Scope = "member", Target = "~M:Cuemon.Extensions.Runtime.Caching.CacheEnumerableExtensions.Memoize``7(Cuemon.Runtime.Caching.ICacheEnumerable{``0},System.TimeSpan,System.Func{``1,``2,``3,``4,``5,``6})~System.Func{``1,``2,``3,``4,``5,``6}")]
