// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_0_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_1_Argument_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_10_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_2_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_3_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_4_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_5_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_6_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_7_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_8_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithActionAsync_Use_9_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_0_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_1_Argument_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_10_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_2_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_3_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_4_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_5_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_6_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_7_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_8_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("ConfigureAwait", "ConfigureAwaitEnforcer:ConfigureAwaitEnforcer", Justification = "<Pending>", Scope = "member", Target = "~M:Cuemon.Diagnostics.TimeMeasureTest.WithFuncAsync_Use_9_Arguments_And_CancellationToken_ShouldTakeAroundOneSecond~System.Threading.Tasks.Task")]
