steps:
  - task: DockerCompose@0
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Take down SQL Server'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: '**/docker-compose.yml'
      dockerComposeCommand: "down"
      action: 'Run a Docker Compose command'