stages:
  - stage: BuildDevelopment
    displayName: 'Build for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Debug'
    jobs:
    - template: ../jobs/build-development.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    dependsOn: BuildDevelopment
    jobs:
    - template: ../jobs/finalization.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: DeployDevelopment
    displayName: 'Deployment for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    dependsOn: UpdateBuildNumber
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-development.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}