stages:
  - stage: BuildPullRequest
    displayName: 'Build for pull request'
    condition: succeeded()
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: ../jobs/build-pullrequest.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for Pull Request'
    condition: and(succeeded(), endsWith(variables['build.reason'], 'pullrequest'))
    dependsOn: BuildPullRequest
    jobs:
    - template: ../jobs/finalization.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}