// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "False-positive; inside try block.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithActionCore``1(Cuemon.ActionFactory{``0},System.Action{Cuemon.Resilience.TransientOperationOptions})")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "False-positive; inside try block.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFuncCore``2(Cuemon.FuncFactory{``0,``1},System.Action{Cuemon.Resilience.TransientOperationOptions})~``1")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "False-positive.", Scope = "member", Target = "~M:Cuemon.Resilience.ActionTransientWorker.ResilientAction(System.Action)")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "False-positive.", Scope = "member", Target = "~M:Cuemon.Resilience.FuncTransientWorker`1.ResilientFunc(System.Func{`0})~`0")]
[assembly: SuppressMessage("Major Code Smell", "S3925:\"ISerializable\" should be implemented correctly", Justification = "MethodBase and Type are not serializable; hence the workaround.", Scope = "type", Target = "~T:Cuemon.Resilience.TransientFaultEvidence")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; generic typed parameters.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithAction``4(System.Action{``0,``1,``2,``3},``0,``1,``2,``3,System.Action{Cuemon.Resilience.TransientOperationOptions})")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; generic typed parameters.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithAction``5(System.Action{``0,``1,``2,``3,``4},``0,``1,``2,``3,``4,System.Action{Cuemon.Resilience.TransientOperationOptions})")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; generic typed parameters.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFunc``4(System.Func{``0,``1,``2,``3},``0,``1,``2,System.Action{Cuemon.Resilience.TransientOperationOptions})~``3")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; generic typed parameters.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFunc``5(System.Func{``0,``1,``2,``3,``4},``0,``1,``2,``3,System.Action{Cuemon.Resilience.TransientOperationOptions})~``4")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; generic typed parameters.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFunc``6(System.Func{``0,``1,``2,``3,``4,``5},``0,``1,``2,``3,``4,System.Action{Cuemon.Resilience.TransientOperationOptions})~``5")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithActionAsync``4(System.Func{``0,``1,``2,``3,System.Threading.CancellationToken,System.Threading.Tasks.Task},``0,``1,``2,``3,System.Action{Cuemon.Resilience.AsyncTransientOperationOptions})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithActionAsync``5(System.Func{``0,``1,``2,``3,``4,System.Threading.CancellationToken,System.Threading.Tasks.Task},``0,``1,``2,``3,``4,System.Action{Cuemon.Resilience.AsyncTransientOperationOptions})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFuncAsync``4(System.Func{``0,``1,``2,System.Threading.CancellationToken,System.Threading.Tasks.Task{``3}},``0,``1,``2,System.Action{Cuemon.Resilience.AsyncTransientOperationOptions})~System.Threading.Tasks.Task{``3}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFuncAsync``5(System.Func{``0,``1,``2,``3,System.Threading.CancellationToken,System.Threading.Tasks.Task{``4}},``0,``1,``2,``3,System.Action{Cuemon.Resilience.AsyncTransientOperationOptions})~System.Threading.Tasks.Task{``4}")]
[assembly: SuppressMessage("Major Code Smell", "S2436:Types and methods should not have too many generic parameters", Justification = "By design; allow up till 5 generic arguments.", Scope = "member", Target = "~M:Cuemon.Resilience.TransientOperation.WithFuncAsync``6(System.Func{``0,``1,``2,``3,``4,System.Threading.CancellationToken,System.Threading.Tasks.Task{``5}},``0,``1,``2,``3,``4,System.Action{Cuemon.Resilience.AsyncTransientOperationOptions})~System.Threading.Tasks.Task{``5}")]
