FROM --platform=$BUILDPLATFORM nginx:1.28.0-alpine AS base
RUN rm -rf /usr/share/nginx/html/*

FROM --platform=$BUILDPLATFORM codebeltnet/docfx:2.78.3 AS build

ADD [".", "docfx"]

RUN cd docfx; \
    docfx build

FROM nginx:1.28.0-alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /build/docfx/wwwroot /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]
