steps:
  - task: DownloadSecureFile@1
    displayName: 'Download cuemon.snk'
    inputs:
      secureFile: 'cuemon.snk'

  - task: CopyFiles@2
    displayName: 'Copy cuemon.snk to $(System.DefaultWorkingDirectory)'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: cuemon.snk
      TargetFolder: '$(System.DefaultWorkingDirectory)'