steps:
  - template: azure-pipelines-jobs-build-step.dotnet.yml

  - template: azure-pipelines-jobs-build-step.minvertool.yml

  - template: azure-pipelines-jobs-build-step.snk.yml

  - template: azure-pipelines-jobs-build-step.minverversionoverride.yml

  - template: azure-pipelines-jobs-build-step.restore.yml

  - task: DotNetCoreCLI@2
    displayName: 'Build netcoreapp3.0 compatible Assemblies'
    inputs:
      command: build
      projects: |
        src/**/Cuemon.AspNetCore*.csproj
        src/**/Cuemon.Extensions.AspNetCore*.csproj
        src/**/Cuemon.Extensions.Hosting.csproj
        src/**/Cuemon.Extensions.Xunit.Hosting.csproj
      arguments: '--configuration $(BuildConfiguration) --verbosity quiet --no-restore --framework netcoreapp3.0'
      workingDirectory: '$(BuildSource)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(BuildSource)'
      artifactName: 'netcoreapp3.0'