steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '**/*.zip' 

  - task: DotNetCoreCLI@2
    condition: succeeded()
    displayName: dotnet pack
    inputs:
      command: pack
      packagesToPack: src/**/*.csproj
      nobuild: true

  - task: PublishPipelineArtifact@1
    condition: succeeded()
    displayName: 'Store NuGet Packages - $(ArtifactPackageName)'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: $(ArtifactPackageName)