jobs:
  - job: 'Finalizer'
    displayName: 'Update BUILD_NUMBER (finalizer)'
    timeoutInMinutes: 10

    pool:
      vmImage: 'ubuntu-20.04'

    steps:

    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK 5.0.103'
      inputs:
        version: 5.0.103

    - task: DotNetCoreCLI@2
      displayName: 'Install MinVer tool'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global minver-cli'

    - script: |
        export MINVERVERSIONOVERRIDE=$(minver)
        echo $MINVERVERSIONOVERRIDE
        echo "##vso[task.setvariable variable=MINVERVERSIONOVERRIDE;]$MINVERVERSIONOVERRIDE"
      displayName: 'Set MINVERVERSIONOVERRIDE (for MinVer)'
      condition: eq(variables['Agent.OS'], 'Linux')

    - script: |
        echo "##vso[build.updatebuildnumber]$MINVERVERSIONOVERRIDE"
      displayName: 'Update BUILD_BUILDNUMBER (for CI flow)'
      condition: eq(variables['Agent.OS'], 'Linux')