jobs:
  - job: DevelopmentBuildDotNet5_0
    displayName: 'Development branch (net5, build, test, code-coverage, code-analysis)'
    timeoutInMinutes: 180
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: 'ubuntu-20.04'
        Windows_Build_Test_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    steps:
    - template: azure-pipelines-jobs-build.net5_0.yml

  - job: DevelopmentBuildDotNet3_1
    displayName: 'Development branch (netcoreapp3.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    steps:
    - template: azure-pipelines-jobs-build.netcoreapp3_1.yml

  - job: DevelopmentBuildDotNet3_0
    displayName: 'Development branch (netcoreapp3.0, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    steps:
    - template: azure-pipelines-jobs-build.netcoreapp3_0.yml

  - job: DevelopmentBuildDotNet2_1
    displayName: 'Development branch (netstandard2.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    steps:
    - template: azure-pipelines-jobs-build.netstandard2_1.yml

  - job: DevelopmentBuildDotNet2_0
    displayName: 'Development branch (netstandard2.0, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    steps:
    - template: azure-pipelines-jobs-build.netstandard2_0.yml

  - job: DevelopmentPublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - DevelopmentBuildDotNet5_0
    - DevelopmentBuildDotNet3_1
    - DevelopmentBuildDotNet3_0
    - DevelopmentBuildDotNet2_1
    - DevelopmentBuildDotNet2_0
    displayName: 'Store NuGet Packages for Preview'
    timeoutInMinutes: 15
    pool:
      vmImage: $(imageName)
    variables:
      - name: ArtifactPackageName
        value: 'Preview'
    steps:
    - template: azure-pipelines-jobs-build-step.nuget.yml