jobs:
  - job: BuildDotNet5_0
    displayName: 'Development branch (net5, build, test, code-coverage, code-analysis)'
    timeoutInMinutes: 180
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: 'ubuntu-20.04'
        Windows_Build_Test_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net5.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.net5_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet3_1
    displayName: 'Development branch (netcoreapp3.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netcoreapp3.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netcoreapp3_1.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet3_0
    displayName: 'Development branch (netcoreapp3.0, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netcoreapp3.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netcoreapp3_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet2_1
    displayName: 'Development branch (netstandard2.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_1.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet2_0
    displayName: 'Development branch (netstandard2.0, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Package:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet5_0
    - BuildDotNet3_1
    - BuildDotNet3_0
    - BuildDotNet2_1
    - BuildDotNet2_0
    displayName: 'Store NuGet Packages for Preview'
    timeoutInMinutes: 15
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: ArtifactPackageName
        value: 'Preview'
    steps:
    - template: azure-pipelines-jobs-build-step.nuget.yml