jobs:
  - job: BuildDotNet6_0
    displayName: 'PR (build, test)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: 'ubuntu-20.04'
        Windows_Build_and_Test:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.reportgenerator.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.dockercomposeup.yml
    - template: azure-pipelines-jobs-build-step.net6_0.yml
    - template: azure-pipelines-jobs-build-step.unittest.yml
    - template: azure-pipelines-jobs-build-step.dockercomposedown.yml

  - job: BuildDotNet3_1
    displayName: 'PR (netcoreapp3.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netcoreapp3.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netcoreapp3_1.yml

  - job: BuildDotNet2_1
    displayName: 'PR (netstandard2.1, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_1.yml

  - job: BuildDotNet2_0
    displayName: 'PR (netstandard2.0, build)'
    timeoutInMinutes: 30
    strategy:
      matrix:
        Linux_Build:
          imageName: 'ubuntu-20.04'
        Windows_Build:
          imageName: 'windows-2019'
    pool:
      vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_0.yml