parameters:
  - name: artifactPackages
    type: object
    default: {}

steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts to be merged for dotnet pack.'
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'src'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - ${{ each ap in parameters.ArtifactPackages }}:
    - pwsh: |
          Expand-Archive '$(System.DefaultWorkingDirectory)\src\${{ap}}.zip' '$(System.DefaultWorkingDirectory)\src' -Force
      displayName: 'Extracting ${{ap}}.zip ..'

  - pwsh: |
        dotnet restore
        dotnet pack --configuration $(BuildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
    displayName: 'Generate NuGet Packages'
    workingDirectory: '$(System.DefaultWorkingDirectory)\src\s'

  - task: PublishBuildArtifacts@1
    condition: succeeded()
    displayName: 'Store NuGet Packages - $(ArtifactPackageName)'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: $(ArtifactPackageName)
      publishLocation: 'Container'