variables:
  - name: DotnetBuildName
    value: 'netcoreapp3.1'

steps:
  - template: azure-pipelines-jobs-build-step.dotnet.yml

  - template: azure-pipelines-jobs-build-step.minvertool.yml

  - template: azure-pipelines-jobs-build-step.snk.yml

  - template: azure-pipelines-jobs-build-step.minverversionoverride.yml

  - template: azure-pipelines-jobs-build-step.restore.yml

  - task: DotNetCoreCLI@2
    displayName: 'Build netcoreapp3.1 compatible Assemblies'
    inputs:
      command: build
      projects: |
        src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.csproj
        src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.Mvc.csproj
        src/**/Cuemon.Extensions.Xunit.App.csproj
      arguments: '--configuration $(BuildConfiguration) --verbosity quiet --no-restore --framework netcoreapp3.1'
      workingDirectory: '$(BuildSource)'

  - template: azure-pipelines-jobs-build-step.artifact.yml