variables:
  - name: DotnetBuildName
    value: 'netstandard2.0'

steps:
  - template: azure-pipelines-jobs-build-step.dotnet.yml

  - template: azure-pipelines-jobs-build-step.minvertool.yml

  - template: azure-pipelines-jobs-build-step.snk.yml

  - template: azure-pipelines-jobs-build-step.minverversionoverride.yml

  - template: azure-pipelines-jobs-build-step.restore.yml

  - task: DotNetCoreCLI@2
    displayName: 'Build netstandard2.0 compatible Assemblies'
    inputs:
      command: build
      projects: |
        src/**/*.csproj
        !src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.csproj
        !src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.Mvc.csproj
        !src/**/Cuemon.Extensions.Xunit.App.csproj
      arguments: '--configuration $(BuildConfiguration) --verbosity quiet --no-restore --framework netstandard2.0'
      workingDirectory: '$(BuildSource)'

  - template: azure-pipelines-jobs-build-step.artifact.yml