jobs:
  - job: 'Production'
    displayName: 'Master branch (build)'
    timeoutInMinutes: 60

    pool:
      vmImage: 'windows-2019'

    steps:

    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK 5.0.201'
      inputs:
        version: 5.0.201

    - task: DotNetCoreCLI@2
      displayName: 'Install MinVer tool'
      inputs:
        command: custom
        custom: tool
        arguments: 'install --global minver-cli'

    - task: DownloadSecureFile@1
      displayName: 'Download cuemon.snk'
      inputs:
        secureFile: 'cuemon.snk'

    - task: CopyFiles@2
      displayName: 'Copy cuemon.snk to $(System.DefaultWorkingDirectory)'
      inputs:
        SourceFolder: '$(Agent.TempDirectory)'
        Contents: cuemon.snk
        TargetFolder: '$(System.DefaultWorkingDirectory)'

    - script: |
        minver > v.txt
        set /p MINVERVERSIONOVERRIDE=<v.txt
        @echo ##vso[task.setvariable variable=MINVERVERSIONOVERRIDE;]%MINVERVERSIONOVERRIDE%
      displayName: 'Set MINVERVERSIONOVERRIDE (for MinVer)'
      condition: eq(variables['Agent.OS'], 'Windows_NT')

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: |
          **/*.csproj

    - task: DotNetCoreCLI@2
      displayName: 'Build Assemblies'
      inputs:
        command: build
        projects: |
          src/**/*.csproj
        arguments: '--configuration $(BuildConfiguration) --no-restore --framework net5.0'
        workingDirectory: '$(BuildSource)'

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: pack
        packagesToPack: src/**/*.csproj
        nobuild: true

    - task: PublishBuildArtifacts@1
      displayName: 'Store NuGet Packages'
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: Production
        publishLocation: Container