parameters:
  - name: artifactPackages
    type: object
    default: {}

steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'src'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - ${{ each ap in parameters.ArtifactPackages }}:
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '**/${{ap}}.zip'
        destinationFolder: '$(System.DefaultWorkingDirectory)'
        cleanDestinationFolder: false 
        overwriteExistingFiles: true

  - task: DotNetCoreCLI@2
    condition: succeeded()
    displayName: dotnet pack
    inputs:
      command: pack
      packagesToPack: src/**/*.csproj
      nobuild: true

  - task: PublishBuildArtifacts@1
    condition: succeeded()
    displayName: 'Store NuGet Packages - $(ArtifactPackageName)'
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: $(ArtifactPackageName)
      publishLocation: 'Container'