steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build netcoreapp3.1 compatible Assemblies'
    inputs:
      command: build
      projects: |
        src/**/Cuemon.AspNetCore*.csproj
        src/**/Cuemon.Extensions.Asp.Versioning.csproj
        src/**/Cuemon.Extensions.AspNetCore*.csproj
        src/**/Cuemon.Extensions.Hosting.csproj
        src/**/Cuemon.Extensions.Swashbuckle.AspNetCore.csproj
        src/**/Cuemon.Extensions.Text.Json.csproj
        src/**/Cuemon.Extensions.Xunit.Hosting.csproj
        src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.csproj
        src/**/Cuemon.Extensions.Xunit.Hosting.AspNetCore.Mvc.csproj
        src/**/Cuemon.Extensions.Xunit.App.csproj
      arguments: '--configuration $(BuildConfiguration) --verbosity quiet --no-restore --framework netcoreapp3.1'
      workingDirectory: '$(BuildSource)'