jobs:
  - job: BuildDotNet6_0
    displayName: 'Master branch (net5.0, build)'
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.net6_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet5_0
    displayName: 'Master branch (net5.0, build)'
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: DotnetBuildName
        value: 'net5.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.net5_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet3_1
    displayName: 'Master branch (netcoreapp3.1, build)'
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: DotnetBuildName
        value: 'netcoreapp3.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netcoreapp3_1.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet2_1
    displayName: 'Master branch (netstandard2.1, build)'
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.1'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_1.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: BuildDotNet2_0
    displayName: 'Master branch (netstandard2.0, build)'
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.0'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.snk.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.restore.yml
    - template: azure-pipelines-jobs-build-step.netstandard2_0.yml
    - template: azure-pipelines-jobs-build-step.artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    - BuildDotNet5_0
    - BuildDotNet3_1
    - BuildDotNet2_1
    - BuildDotNet2_0
    displayName: 'Store NuGet Packages for Production'
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: ArtifactPackageName
        value: 'Production'
    steps:
    - template: azure-pipelines-jobs-build-step.dotnet.yml
    - template: azure-pipelines-jobs-build-step.minvertool.yml
    - template: azure-pipelines-jobs-build-step.minverversionoverride.yml
    - template: azure-pipelines-jobs-build-step.nuget.yml
      parameters:
        artifactPackages:
          - "net6.0"
          - "net5.0"
          - "netcoreapp3.1"
          - "netstandard2.1"
          - "netstandard2.0"