steps:
  - task: ArchiveFiles@2
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      archiveFile: $(Build.ArtifactStagingDirectory)/$(DotnetBuildName).zip

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/$(DotnetBuildName).zip
      artifactName: 'src'
      publishLocation: 'Container'