jobs:
  - deployment: 'CD'
    displayName: 'Release to public NuGet Feed'
    environment: 'Production'
    pool:
      vmImage: 'ubuntu-22.04'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Production'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://api.nuget.org/v3/index.json'
              inputs:
                command: custom
                arguments: 'push $(System.DefaultWorkingDirectory)/**/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $(nuget-org-apikey) -SkipDuplicate'