stages:
  - stage: BuildPullRequest
    displayName: 'Build for pull request'
    condition: succeeded()
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: azure-pipelines-jobs-build.pullrequest.yml

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for Pull Request'
    condition: and(succeeded(), endsWith(variables['build.reason'], 'pullrequest'))
    dependsOn: BuildPullRequest
    jobs:
    - template: azure-pipelines-jobs-finalization.yml