stages:
  - stage: BuildRelease
    displayName: 'Build for release branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'release'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: azure-pipelines-build.staging.yml

  - stage: DeployRelease
    displayName: 'Deployment for release branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'release'))
    dependsOn: BuildRelease
    variables:
    - group: BuildSecrets
    jobs:
    - template: azure-pipelines-deployment.staging.yml