jobs:
  - deployment: 'CD'
    displayName: 'Preview: release to private NuGet Feed'
    environment: 'Development'
    pool:
      vmImage: 'ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Preview'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://nuget.cuemon.net/v3/index.json'
              inputs:
                command: push
                packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;$(System.DefaultWorkingDirectory)/**/*.snupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'Cuemon-Nuget'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://nuget.pkg.github.com/gimlichael/index.json'
              inputs:
                command: push
                packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;$(System.DefaultWorkingDirectory)/**/*.snupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'Cuemon-NugetGit'