jobs:
  - job: BuildDotNet8_0
    displayName: 'Master branch (net8.0, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net8.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net8_0.yml
    - template: ../steps/publish-artifact.yml

  - job: BuildDotNet7_0
    displayName: 'Master branch (net7.0, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net7.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net7_0.yml
    - template: ../steps/publish-artifact.yml

  - job: BuildDotNet6_0
    displayName: 'Master branch (net6.0, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/publish-artifact.yml

  - job: BuildDotNetStandard2_1
    displayName: 'Master branch (netstandard2.1, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.1'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-netstandard2_1.yml
    - template: ../steps/publish-artifact.yml

  - job: BuildDotNetStandard2_0
    displayName: 'Master branch (netstandard2.0, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: DotnetBuildName
        value: 'netstandard2.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-netstandard2_0.yml
    - template: ../steps/publish-artifact.yml


  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet8_0
    - BuildDotNet7_0
    - BuildDotNet6_0
    - BuildDotNetStandard2_1
    - BuildDotNetStandard2_0
    displayName: 'Store NuGet Packages for Production'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.linuxVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.linuxVmImage }}
    variables:
      - name: ArtifactPackageName
        value: 'Production'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactPackages:
          - "net8.0"
          - "net7.0"
          - "net6.0"
          - "netstandard2.1"
          - "netstandard2.0"
