jobs:
  - job: BuildDotNet8_0
    displayName: 'PR (net8, build)'
    timeoutInMinutes: 60
    strategy:
      matrix:
        Linux_Build:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net8.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net8_0.yml

  - job: BuildDotNet7_0
    displayName: 'PR (net7, build)'
    timeoutInMinutes: 60
    strategy:
      matrix:
        Linux_Build:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net7.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net7_0.yml

  - job: BuildDotNet6_0
    displayName: 'PR (net6, build)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build_Test_and_Package:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml