jobs:
  - deployment: CD
    displayName: 'Preview: release to public NuGet Feed'
    environment: 'Development'
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.linuxVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.linuxVmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Preview'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetToolInstaller@1
              displayName: Install NuGet
              inputs:
                versionSpec: 6.7.0

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://api.nuget.org/v3/index.json'
              inputs:
                command: custom
                arguments: 'push $(System.DefaultWorkingDirectory)/**/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $(nuget-org-apikey) -SkipDuplicate'