name: Cuemon CI/CD Pipeline
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .codecov/**
      - .docfx/**
      - .github/**
      - .nuget/**
      - '**.md'
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: The build configuration to use in the deploy stage.
        required: true
        default: Release
        options:
          - Debug
          - Release
      projects:
        type: string
        description: Projects to iterate in test
        default: "test/**/Cuemon.AspNetCore.Mvc.FunctionalTests.csproj test/**/Cuemon.AspNetCore.Mvc.Tests.csproj"
      level:
        type: choice
        description: Desired loglevel for test
        default: Normal
        options:
          - Normal
          - Quiet
          - Minimal
          - Detailed
          - Diagnostic
      blameHangTimeout:
        type: string
        description: The time to wait for a test to complete before collecting a dump. Default is 10 minutes.
        default: '10m'
      blameHangDumpType:
        type: string
        description: The type of dump to collect when a test hangs. Default is mini.
        default: 'mini'

jobs:
  prepare_linux:
    name: 🐧 Prepare Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    outputs:
      restoreCacheKey: ${{ steps.dotnet-restore.outputs.restoreCacheKey }}
    steps:
      - name: Checkout
        uses: codebeltnet/git-checkout@v1

      - name: Install .NET
        uses: codebeltnet/install-dotnet@v1
        with:
          includePreview: true

      - id: dotnet-restore
        name: Restore Dependencies
        uses: codebeltnet/dotnet-restore@v2
        with:
          useRestoreCache: true

  prepare_windows:
    name: 🪟 Prepare Windows
    runs-on: windows-2022
    timeout-minutes: 15
    outputs:
      restoreCacheKey: ${{ steps.dotnet-restore.outputs.restoreCacheKey }}
    steps:
      - name: Checkout
        uses: codebeltnet/git-checkout@v1

      - name: Install .NET
        uses: codebeltnet/install-dotnet@v1
        with:
          includePreview: true

      - id: dotnet-restore
        name: Restore Dependencies
        uses: codebeltnet/dotnet-restore@v2
        with:
          useRestoreCache: true

  build:
    name: 🛠️ Build
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      matrix:
        configuration: [Debug, Release]
        framework: [net9.0, net8.0, net6.0, netstandard2.1, netstandard2.0]
    needs: [prepare_linux]
    outputs:
      version: ${{ steps.minver-calculate.outputs.version }}
      testProjects: ${{ steps.test-projects.outputs.result }}
    steps:
      - name: Checkout
        uses: codebeltnet/git-checkout@v1
      
      - name: Install .NET
        uses: codebeltnet/install-dotnet@v1
        with:
          includePreview: true

      - name: Install MinVer
        uses: codebeltnet/dotnet-tool-install-minver@v1

      - id: minver-calculate
        name: Calculate Version
        uses: codebeltnet/minver-calculate@v2

      - name: Download cuemon.snk file
        uses: codebeltnet/gcp-download-file@v1
        with:
          serviceAccountKey: ${{ secrets.GCP_TOKEN }}
          bucketName: ${{ secrets.GCP_BUCKETNAME }}
          objectName: cuemon.snk

      - name: Set environment variable for projects
        run: |
          if [ "${{ matrix.framework }}" == "netstandard2.1" ]; then
            echo "PROJECTS=src/**/Cuemon.Extensions.IO.csproj src/**/Cuemon.IO.csproj" >> $GITHUB_ENV
          elif [ "${{ matrix.framework }}" == "netstandard2.0" ]; then
            projects=(
              "src/**/Cuemon.Core.csproj"
              "src/**/Cuemon.Data.csproj"
              "src/**/Cuemon.Data.Integrity.csproj"
              "src/**/Cuemon.Data.SqlClient.csproj"
              "src/**/Cuemon.Diagnostics.csproj"
              "src/**/Cuemon.Extensions.Collections.Generic.csproj"
              "src/**/Cuemon.Extensions.Collections.Specialized.csproj"
              "src/**/Cuemon.Extensions.Core.csproj"
              "src/**/Cuemon.Extensions.Data.csproj"
              "src/**/Cuemon.Extensions.Data.Integrity.csproj"
              "src/**/Cuemon.Extensions.DependencyInjection.csproj"
              "src/**/Cuemon.Extensions.Diagnostics.csproj"
              "src/**/Cuemon.Extensions.Globalization.csproj"
              "src/**/Cuemon.Extensions.Hosting.csproj"
              "src/**/Cuemon.Extensions.IO.csproj"
              "src/**/Cuemon.Extensions.Net.csproj"
              "src/**/Cuemon.Extensions.Newtonsoft.Json.csproj"
              "src/**/Cuemon.Extensions.Reflection.csproj"
              "src/**/Cuemon.Extensions.Runtime.Caching.csproj"
              "src/**/Cuemon.Extensions.Text.csproj"
              "src/**/Cuemon.Extensions.Threading.csproj"
              "src/**/Cuemon.Extensions.Xml.csproj"
              "src/**/Cuemon.Extensions.Xunit.csproj"
              "src/**/Cuemon.Extensions.Xunit.Hosting.csproj"
              "src/**/Cuemon.Extensions.YamlDotNet.csproj"
              "src/**/Cuemon.IO.csproj"
              "src/**/Cuemon.Net.csproj"
              "src/**/Cuemon.Resilience.csproj"
              "src/**/Cuemon.Runtime.Caching.csproj"
              "src/**/Cuemon.Security.Cryptography.csproj"
              "src/**/Cuemon.Threading.csproj"
              "src/**/Cuemon.Xml.csproj"
            )
            echo "PROJECTS=$(IFS=' '; echo "${projects[*]}")" >> $GITHUB_ENV
          else
            echo "PROJECTS=src/**/*.csproj" >> $GITHUB_ENV
          fi
        shell: bash

      - id: dotnet-build
        name: Build for ${{ matrix.framework }} (${{ matrix.configuration }})
        uses: codebeltnet/dotnet-build@v2
        with:
          projects: ${{ env.PROJECTS }}
          configuration: ${{ matrix.configuration }}
          framework: ${{ matrix.framework }}
          restoreCacheKey: ${{ needs.prepare_linux.outputs.restoreCacheKey }}

  test:
    name: 🧪 Test
    needs: [build, prepare_linux, prepare_windows]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: codebeltnet/git-checkout@v1

      - name: Install .NET
        uses: codebeltnet/install-dotnet@v1
        with:
          includePreview: true

      - name: Install .NET Tool - Report Generator
        uses: codebeltnet/dotnet-tool-install-reportgenerator@v1

      - if: ${{ runner.os == 'Linux' && needs.prepare_linux.outputs.restoreCacheKey || needs.prepare_windows.outputs.restoreCacheKey }}
        name: Restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}
            !${{ github.workspace }}/.git
            ~/.nuget/packages
          key: ${{ runner.os == 'Linux' && needs.prepare_linux.outputs.restoreCacheKey || needs.prepare_windows.outputs.restoreCacheKey }}
          restore-keys: |
            dotnet-restore-
          enableCrossOsArchive: true
          fail-on-cache-miss: true
  
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*-${{ matrix.configuration }}'
          merge-multiple: true
  
      - name: Test
        run: |
            shopt -s globstar extglob
            for file in ${{ inputs.projects }}; do
              dotnet test $file --configuration ${{ matrix.configuration }} --verbosity ${{ inputs.level }} --logger trx --results-directory $RUNNER_TEMP/TestResults --collect:"XPlat Code Coverage;Format=opencover" --blame-hang-timeout ${{ inputs.blameHangTimeout }} --blame-hang-dump-type ${{ inputs.blameHangDumpType }} -p:CoverletOutputFormat=opencover -p:UseSourceLink=true -bl --diag:$RUNNER_TEMP/TestResults/logs/log.txt
              echo "Tested and written results for '$file'"
            done
        shell: bash
  
      - name: Use Report Generator
        run: reportgenerator "-reports:$RUNNER_TEMP/TestResults/**/*.opencover.xml" "-targetdir:${{ github.workspace }}/Coverage" "-reporttypes:Cobertura;MarkdownSummaryGithub;HTMLInline;HTMLChart"
        shell: bash
  
      - name: Upload TestResults
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{ inputs.configuration }}-${{ runner.os }}-${{ hashFiles(inputs.projects) }}
          path: ${{ runner.temp }}/TestResults
          include-hidden-files: true
